### ISSUE TITLE
features/typescript - first exercise is incorrect

### ISSUE THREAD

**Issue by tyllrb** [rangle/ngCourse2#107]
The first exercise in the features/typescript exercise section does not work - there is no correct solution.

**Comment by SethDavenport** [comment]
@tyllrb which exercise are you talking about?  the 'pizza topics' code sample from the book content or something else?

**Comment by SethDavenport** [comment]
Nevermind, found it.  `exercises/features/typescript/1.0-primitive-types_solution has a type error:

```typescript
type numOrString = number | string;

// ...

function write(...args: numOrString[]) {
    const element = document.getElementById('example');
    element.innerHTML += args.reduce((prev, curr) => prev + curr + ' ', '');
}
```

Typescript complains that `operator + cannot be applied to types (number | string)` - effectively it's not recognizing our custom type `numOrString` as "plus-able".

The error can be fixed by making it explicit that we want string concatenation as follows:

```typescript
function write(...args: numOrString[]) {
    const element = document.getElementById('example');
    element.innerHTML += args.reduce((prev: string, curr: string) => prev + curr + ' ', '');
}
```

However I'm actually surprised TypeScript accepts this, considering that it introduces an implied type coercion from `numOrString` to `string`, which seems unsafe in the general case.

This is a case where we actually want a coercion to string in all cases.  So I'm thinking we should amend the solution to be explicit by using a typecast. This would also be an opportunity to talk about typecasting in TypeScript:

```typescript
function write(...args: numOrString[]) {
    const element = document.getElementById('example');
    element.innerHTML += args.reduce((prev, curr) => <string> prev + <string> curr + ' ', '');
  }
```

@bennett000 thoughts?
