### ISSUE TITLE
Update Redux version of app to use ng2-redux v3

### ISSUE THREAD

**Issue by e-schultz** [rangle/ngCourse2#218]

**Comment by mdegani** [comment]
@e-schultz the app does not use redux to manage state for it's main features.  There are reducers and actions for counter functionality which seems to have been left in the app from the starter on which it was built.  This 

Do we want to introduce redux to manage state instead of the approach taken in this service: https://github.com/rangle/ngCourse2/blob/master/app/src/services/tasks-service.ts

**Comment by e-schultz** [comment]
App has been removed from repo, card no longer relevant
