### ISSUE TITLE
Forms: talk about CSS validation classes

### ISSUE THREAD

**Issue by SethDavenport** [rangle/ngCourse2#624]
We don't talk about these anywhere, but they're very useful.  When a for field is dirty, invalid, etc. Angular automatically applies `ng-dirty`, `ng-valid` etc. CSS classes to it. By providing definitions for these classes, and combinations of them, you have a quick visual feedback mechanism for very little code.

I would hate to see more people writing complicated ngClass stuff when the built-ins already do it for you...

**Comment by seanmay** [comment]
I concur. This (and orthogonal properties on the input elements) are WiPs that I hid away for the sake of having complete practical stuff for you, tomorrow.

I was sort of planning to have that be a piece of my tomorrow, along with a real example of observable inputs (the old chapter just seemed to say "hey there are streams of updates you can listen to on input", undoubtedly due to similar time constraints and knowledge gaps).
I also know that there's an even more terse (and thus less likely to cause headaches due to Angular-alchemy) syntax for FormBuilder, but I failed to get it working as expected.

These were my Wednesday, unless there are issues better tackled, elsewhere.
