### ISSUE TITLE
Include fringe ngCourse content that we don't cover yet.

### ISSUE THREAD

**Issue by gillianml** [rangle/ngCourse2#716]
In the August 31 support squad weekly, Michael Bennett raised that it would be worthwhile to cover fringe content such as:
- universal
- CLI
- host bindings
- translations
- localization
  
  Because it will affect our client projects.

Also, make sure that all Rangle.io devs know about our solution:
- Rangle Weekly
- A2 Guild
- A2 channel

We can work on this content once google's solutions for these stabilize

**Comment by e-schultz** [comment]
### Directives

* Directives - general

We don't cover directives that much, and lightly touch on using the existing ones. We don't talk about why/when you would want to create a directive.

Directives are used to add behavior to a component/element, Directives can also be used to modify the appearance of an element, but does not have a template on their own.

* Host Binding - properties
  * Should have a clear example
  * Should provide practical usecase(s)
  * Should have a value-add over the API docs - https://angular.io/docs/ts/latest/api/core/index/HostBindingMetadata-class.html
* Host Listening - events 
  * Should have a clear example
  * Should provide practical usecase(s)
  * Should have a value-add over the API docs - https://angular.io/docs/ts/latest/api/core/index/HostListenerMetadata-class.html

  ### NgModule

  Our current content on NgModule is pretty basic -  probably room to expand this out:

  * Module architecture / what to make it's own module
  * etc?

 ### Services/Providers 

  * Use case for non-singleton providers / @Host in components/directives

  Most services that people create can be fine as singletons for the application, however there can be times when having an instance per-component can be useful. We don't really cover this other than to say that it can be done. A use case that Nik has been working on is handling errors

  ```html
  <error-container> <-- has a service that is insanced per error-container, not singleton
    <individual-error></individual-error> - uses @Host to get access to the service for communication
  </error-container>
  ```

  If we can get a way of making this easy to explain/digest - could be a useful addition. Maybe frame it more of a 'component communication patterns'?

  ### Forms 

  * Validation Directives 

  We cover creating a custom validator, but not how to make one as a directive so that it can be used with template-driven forms. Can probably take the current 'custom validation' example / text - and then expand on it to be available as a directive/template validator.

  ### i18n 

  Details are starting to come out about localization, came across this example repo - https://github.com/StephenFluin/i18n-sample, looks like the official i18n solution is using the XILF file format

  Basic details in this blog post: http://angularjs.blogspot.ca/2016/09/angular-2-rc6_1.html

  * use of ng-xi18n to extract out symbols 

  ### Animations

  We don't really cover it at all - even if this doesn't become part of what we cover in training, is there value in adding material to the book on this?

  ### General Thoughts

  Look at our content / examples / etc - consider:

  * Is real-world / practical - or contrived examples?
  * Is it providing a relatable use case that most people can understand?
  * What do we provide beyond the official docs?

  As the official documentation/cookbooks/guides improve - having a value beyond explaining "this is what the API is with a example that doesn't reflect real-world use" is more important.

**Comment by bennett000** [comment]
At this point we've covered this card in other stories
