### ISSUE TITLE
Update Code Examples/plunkers to 2.0

### ISSUE THREAD

**Issue by bennett000** [rangle/ngCourse2#759]
- [x] Bootstrapping (Troy)
- [x] Components in Angular 2 (Alejandro)
- [x] Directives (Sonu)
- [x] Advanced Components (Troy)
- [x] Observables (Troy)
- [x] Change Detection (Troy)
- [x] Advanced Angular (Troy)
- [x] Dependency Injection (Sonu)
- [x] Pipes (Sonu)
- [x] Forms (Sonu)
- [x] Routing (Troy)
- [x] Redux and Ngrx (Troy)
- [x] Testing (Troy)
- [x] Modules (Troy)

The [examples](https://github.com/rangle/ngCourse2/tree/master/examples "ngCourse2 examples") will need to be updated.

Additionally all of the plunkers which are based on these examples need to be updated.  

The addresses of the existing plunkers can be found by looking through the "handout" section of the book for URLs.

If you did _not_ create the existing plunker you will need to fork the plunker and update the link in the ebook.

**Comment by Kirfkin** [comment]
I think this should cover the one major issue I've found with the examples in the book thus far (should fall under the Components section; in particular "Access Child Components From the Template pp. 72-3) where the [plunker project](https://plnkr.co/edit/UTBleHSpTf5To8zZSbSd?p=preview) did not run. I have not had time to personally investigate the issue to resolve it myself, nor am I sure it warrants its own issue since it now seems related to this enhancement issue.

-- Thomas
